package pt.cienciasinvestimento.chatbot.domain;

public enum Intent {
    TRAINING_INFO,
    PAYMENT_GENERAL,
    ACCESS_GENERAL,
    PASSWORD_RECOVERY,
    SUBSCRIPTION_GENERAL,
    CERTIFICATION,
    PERSONAL_ACCOUNT_ISSUE,
    FINANCIAL_ADVICE_BLOCKED,
    HUMAN_SUPPORT,
    UNKNOWN
}
